### ISSUE TITLE
Help: 

### ISSUE THREAD

**Issue by SouvikGhosh05** [QuizApi/QuizAPI-BASH#7]
### Need help with parameters
Hi, I just checked out Quiz API documentation thoughly, see like this below...
```
curl https://quizapi.io/api/v1/questions -G \
-d apiKey=YOUR_API_KEY \
-d limit=10
```
I passed the optional _limit_ parameter but, the responses I'm getting is too long and more that the required limit. If I want to get only 2 questions, I'm getting more that 25 questions in the json file. And also the _category_ parameter is not working, I'm getting questions from other category also.

**Comment by QuizAPI-Support** [comment]
Hi,

All that you need to do is to change the `YOUR_API_KEY` part with your actual API key:

```
curl https://quizapi.io/api/v1/questions -G \
-d apiKey=YOUR_API_KEY \
-d limit=10
```

Or you could pass the following header with any framework or language: 

`'X-Api-Key: YOUR_API_KEY'`

you can also visit the URL directly via your browser:

https://quizapi.io/api/v1/questions?apiKey=YOUR_API_KEY

This is a totally free api and it is very disappointing to see such comments just because you can’t get the authentication right.

**Comment by SouvikGhosh05** [comment]
Sorry, I said API key worked, I included in headers as it is needed but the parameters are not working that I said. If I create a querystring like this, 

`{'X-Api-Key': YOUR_API_KEY}
querystring ={ 'category' : 'linux', 
                          'limit' : '2'} 
response= request.get(url="....", params=querystring, headers=headers)`
I did exactly what category of question I searched for, in this case it is Linux and it was more that 2 questions I'm getting with the response since the limit I set as 2. So the parameters are not working. How to handle with this?
